# Adds labels to pull requests based on the size of the changes (changed lines)

# ðŸ· Pull Request Size Labeler
# https://github.com/marketplace/actions/pull-request-size-labeler

name: ðŸŒˆ Label PR Size

on: [pull_request]

jobs:
  labeler:
    permissions:
      pull-requests: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          xs_label: 'PR - Small'
          xs_max_size: '1'
          s_label: 'PR - Small'
          s_max_size: '100'
          m_label: 'PR - Medium'
          m_max_size: '500'
          l_label: 'PR - Large'
          l_max_size: '1000'
          xl_label: 'PR - XL'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are not addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          github_api_url: 'https://api.github.com'
          files_to_ignore: |
            "package-lock.json"
            "public/lib/*"
