name: ğŸ¯ Issues Auto Manager

on:
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  label-on-content:
    name: Auto-Label Issues (Based on Issue Content)
    runs-on: ubuntu-latest

    steps:
      - name: Auto-Label Issues (Based on Issue Content)
        # only auto label based on issue content once, on open (to prevent re-labeling removed labels)
        if: github.event.action == 'opened'

        # Issue Labeler
        # https://github.com/marketplace/actions/regex-issue-labeler
        uses: github/issue-labeler@v3
        with:
          configuration-path: .github/issues-auto-labels.yml
          enable-versioned-regex: 0
          repo-token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

  label-on-labels:
    name: Auto-Label Issues (Based on Issue Labels)
    runs-on: ubuntu-latest

    steps:
      - name: âœ… Add "ğŸ‘ Approved" for relevant labels
        if: contains(fromJSON('["ğŸ‘©â€ğŸ’» Good First Issue", "ğŸ™ Help Wanted", "ğŸª² Confirmed", "âš ï¸ High Priority", "â• Medium Priority", "ğŸ’¤ Low Priority"]'), github.event.label.name)
        # ğŸ¤– Issues Helper
        # https://github.com/marketplace/actions/issues-helper
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          labels: 'ğŸ‘ Approved'

      - name: âŒ Remove progress labels when issue is marked done or stale
        if: contains(fromJSON('["âœ… Done", "âœ… Done (staging)", "âš°ï¸ Stale", "âŒ wontfix"]'), github.event.label.name)
        # ğŸ¤– Issues Helper
        # https://github.com/marketplace/actions/issues-helper
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          labels: 'ğŸ§‘â€ğŸ’» In Progress,ğŸ¤” Unsure,ğŸ¤” Under Consideration'

      - name: âŒ Remove temporary labels when confirmed labels are added
        if: contains(fromJSON('["âŒ wontfix","ğŸ‘ Approved","ğŸ‘©â€ğŸ’» Good First Issue"]'), github.event.label.name)
        # ğŸ¤– Issues Helper
        # https://github.com/marketplace/actions/issues-helper
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          labels: 'ğŸ¤” Unsure,ğŸ¤” Under Consideration'

      - name: âŒ Remove no bug labels when "ğŸª² Confirmed" is added
        if: github.event.label.name == 'ğŸª² Confirmed'
        # ğŸ¤– Issues Helper
        # https://github.com/marketplace/actions/issues-helper
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          labels: 'âœ–ï¸ Not Reproducible,âœ–ï¸ Not A Bug'

  write-auto-comments:
    name: Post Issue Comments Based on Labels
    needs: [label-on-content, label-on-labels]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        # Checkout
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v4

      - name: Post Issue Comments Based on Labels
        # Label Commenter
        # https://github.com/marketplace/actions/label-commenter
        uses: peaceiris/actions-label-commenter@v1
        with:
          config_file: .github/issues-auto-comments.yml
          github_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
