name: ğŸ¯ Issues Auto Manager

on:
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  issue-label-on-content:
    name: Auto-Label Issues (Based on Issue Content)
    runs-on: ubuntu-latest

    steps:
      - name: Auto-Label Issues (Based on Issue Content)
        # Issue Labeler
        # https://github.com/marketplace/actions/regex-issue-labeler
        uses: github/issue-labeler@v3
        with:
          configuration-path: .github/issues-auto-labels.yml
          enable-versioned-regex: 0
          repo-token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

  issue-label-on-labels:
    name: Auto-Label Issues (Based on Issue Labels)
    runs-on: ubuntu-latest

    steps:
      # âœ… Auto-Add "ğŸ‘ Approved / Nice-to-Have" when specific labels are added
      - name: Add "ğŸ‘ Approved / Nice-to-Have" for relevant labels
        if: contains(fromJSON('["ğŸ‘©â€ğŸ’» Good First Issue", "ğŸ™ Help Wanted", "ğŸª² Confirmed", "âš ï¸ High Priority", "â• Medium Priority", "ğŸ’¤ Low Priority"]'), github.event.label.name)
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          labels: 'ğŸ‘ Approved / Nice-to-Have'

      # âŒ Remove "ğŸ§‘â€ğŸ’» In Progress" when specific labels are added
      - name: Remove "ğŸ§‘â€ğŸ’» In Progress" when PR is marked done or stale
        if: contains(fromJSON('["âœ… Done", "âœ… Done (staging)", "âš°ï¸ Stale", "âŒ wontfix"]'), github.event.label.name)
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          labels: 'ğŸ§‘â€ğŸ’» In Progress'

      # âŒ Remove "ğŸ¤” Unsure" and "ğŸ¤” Under Consideration" when "âŒ wontfix" is added
      - name: Remove "ğŸ¤” Unsure" and "ğŸ¤” Under Consideration" when "âŒ wontfix" is added
        if: github.event.label.name == 'âŒ wontfix'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          labels: 'ğŸ¤” Unsure,ğŸ¤” Under Consideration'

  issue-auto-comments:
    name: Post Issue Comments Based on Labels
    needs: [issue-label-on-content, issue-label-on-labels]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        # Checkout
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v4

      - name: Post Issue Comments Based on Labels
        # Label Commenter
        # https://github.com/marketplace/actions/label-commenter
        uses: peaceiris/actions-label-commenter@v1
        with:
          config_file: .github/issues-auto-comments.yml
          github_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
